<<<<<<< HEAD
You tried to access the file "pdb_molecule" in the request.files dictionary but it does not exist.  The mimetype for the request is "application/x-www-form-urlencoded" instead of "multipart/form-data" which means that no file contents were transmitted.  To fix this error you should provide enctype="multipart/form-data" in your form.

The browser instead transmitted some file names. This was submitted: ""
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/debughelpers.py", line 96, in __getitem__
    return oldcls.__getitem__(self, key)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 100, in form_handler
    pdb_file = request.files["pdb_molecule"]
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/debughelpers.py", line 100, in __getitem__
    raise DebugFilesKeyError(request, key)
flask.debughelpers.DebugFilesKeyError: You tried to access the file "pdb_molecule" in the request.files dictionary but it does not exist.  The mimetype for the request is "application/x-www-form-urlencoded" instead of "multipart/form-data" which means that no file contents were transmitted.  To fix this error you should provide enctype="multipart/form-data" in your form.

The browser instead transmitted some file names. This was submitted: ""
You tried to access the file "pdb_molecule" in the request.files dictionary but it does not exist.  The mimetype for the request is "application/x-www-form-urlencoded" instead of "multipart/form-data" which means that no file contents were transmitted.  To fix this error you should provide enctype="multipart/form-data" in your form.

The browser instead transmitted some file names. This was submitted: ""
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/debughelpers.py", line 96, in __getitem__
    return oldcls.__getitem__(self, key)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 100, in form_handler
    pdb_file = request.files["pdb_molecule"]
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/debughelpers.py", line 100, in __getitem__
    raise DebugFilesKeyError(request, key)
flask.debughelpers.DebugFilesKeyError: You tried to access the file "pdb_molecule" in the request.files dictionary but it does not exist.  The mimetype for the request is "application/x-www-form-urlencoded" instead of "multipart/form-data" which means that no file contents were transmitted.  To fix this error you should provide enctype="multipart/form-data" in your form.

The browser instead transmitted some file names. This was submitted: ""
You tried to access the file "pdb_molecule" in the request.files dictionary but it does not exist.  The mimetype for the request is "application/x-www-form-urlencoded" instead of "multipart/form-data" which means that no file contents were transmitted.  To fix this error you should provide enctype="multipart/form-data" in your form.

The browser instead transmitted some file names. This was submitted: ""
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/debughelpers.py", line 96, in __getitem__
    return oldcls.__getitem__(self, key)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 101, in form_handler
    pdb_file = request.files["pdb_molecule"]
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/debughelpers.py", line 100, in __getitem__
    raise DebugFilesKeyError(request, key)
flask.debughelpers.DebugFilesKeyError: You tried to access the file "pdb_molecule" in the request.files dictionary but it does not exist.  The mimetype for the request is "application/x-www-form-urlencoded" instead of "multipart/form-data" which means that no file contents were transmitted.  To fix this error you should provide enctype="multipart/form-data" in your form.

The browser instead transmitted some file names. This was submitted: ""
You tried to access the file "pdb_molecule" in the request.files dictionary but it does not exist.  The mimetype for the request is "application/x-www-form-urlencoded" instead of "multipart/form-data" which means that no file contents were transmitted.  To fix this error you should provide enctype="multipart/form-data" in your form.

The browser instead transmitted some file names. This was submitted: ""
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/debughelpers.py", line 96, in __getitem__
    return oldcls.__getitem__(self, key)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 101, in form_handler
    pdb_file = request.files["pdb_molecule"]
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/debughelpers.py", line 100, in __getitem__
    raise DebugFilesKeyError(request, key)
flask.debughelpers.DebugFilesKeyError: You tried to access the file "pdb_molecule" in the request.files dictionary but it does not exist.  The mimetype for the request is "application/x-www-form-urlencoded" instead of "multipart/form-data" which means that no file contents were transmitted.  To fix this error you should provide enctype="multipart/form-data" in your form.

The browser instead transmitted some file names. This was submitted: ""
=======
>>>>>>> c915717735655db297344124c1b2db5cae160044
400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 99, in form_handler
    force_field = request.form["force_field"]
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 99, in form_handler
    force_field = request.form["force_field"]
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 99, in form_handler
    force_field = request.form["force_field"]
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 99, in form_handler
    force_field = request.form["force_field"]
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 99, in form_handler
    force_field = request.form["force_field"]
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 99, in form_handler
    force_field = request.form["force_field"]
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 99, in form_handler
    force_field = request.form["force_field"]
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 99, in form_handler
    force_field = request.form["force_field"]
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 99, in form_handler
    force_field = request.form["force_field"]
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 101, in form_handler
    force_field = request.form["force_field"]
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 101, in form_handler
    force_field = request.form["force_field"]
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 101, in form_handler
    force_field = request.form["force_field"]
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 99, in form_handler
    force_field = request.form["force_field"]
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1953, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1968, in finalize_request
    response = self.make_response(rv)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 2097, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 101, in form_handler
    force_field = request.form["force_field"]
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 101, in form_handler
    force_field = request.form["force_field"]
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 101, in form_handler
    force_field = request.form["force_field"]
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/et/personal_projects/rdkit-obabel-confgen/flask_app.py", line 101, in form_handler
    force_field = request.form["force_field"]
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/datastructures.py", line 442, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.
KeyError: 'force_field'
405 Method Not Allowed: The method is not allowed for the requested URL.
Traceback (most recent call last):
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1926, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/app.py", line 1908, in raise_routing_exception
    raise request.routing_exception
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/flask/ctx.py", line 350, in match_request
    result = self.url_adapter.match(return_rule=True)
  File "/home/et/miniconda3/envs/flaskenv/lib/python3.8/site-packages/werkzeug/routing.py", line 1940, in match
    raise MethodNotAllowed(valid_methods=list(have_match_for))
werkzeug.exceptions.MethodNotAllowed: 405 Method Not Allowed: The method is not allowed for the requested URL.
